# Generated by Django 4.2.16 on 2024-09-13 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
