# Generated by Django 4.2.16 on 2024-09-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0003_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='equity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='free_margin',
            field=models.FloatField(default=0),
        ),
    ]
