# Generated by Django 4.2.16 on 2024-09-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0004_statistic_equity_statistic_free_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='commission_profit',
            field=models.FloatField(default=0),
        ),
    ]
