# Generated by Django 4.2.16 on 2024-09-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0005_statistic_commission_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='commission_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
