# Generated by Django 4.2.16 on 2024-10-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0006_statistic_commission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='margin',
            field=models.FloatField(default=0),
        ),
    ]
