# Generated by Django 4.2.16 on 2024-10-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0007_statistic_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='margin_level',
            field=models.FloatField(default=0),
        ),
    ]
