# Generated by Django 4.2.16 on 2024-10-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0010_withdrawalrequest_exchange_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='reason_for_rejection',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
