# Generated by Django 4.2.16 on 2024-10-03 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0011_remove_withdrawalrequest_reason_for_rejection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawalrequest',
            old_name='amunt',
            new_name='amount',
        ),
    ]
