# Generated by Django 4.2.16 on 2024-10-03 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('state', '0012_rename_amunt_withdrawalrequest_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='request_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
