# Generated by Django 4.2.16 on 2024-10-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0013_alter_statistic_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='max_withdraw',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='statistic',
            name='min_withdraw',
            field=models.IntegerField(default=100),
        ),
    ]
