# Generated by Django 4.2.16 on 2024-10-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0015_alter_statistic_min_withdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='max_withdraw',
            field=models.IntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='min_withdraw',
            field=models.IntegerField(default=10),
        ),
    ]
