# Generated by Django 4.2.16 on 2024-10-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0018_alter_statistic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='balance',
            field=models.FloatField(default=1),
        ),
    ]
