# Generated by Django 4.2.16 on 2024-10-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0019_alter_statistic_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='swap_off_ratio',
            field=models.FloatField(default=1),
        ),
    ]
