# Generated by Django 4.2.16 on 2024-10-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0020_statistic_swap_off_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='commission_off_ratio',
            field=models.FloatField(default=1),
        ),
    ]
