# Generated by Django 4.2.16 on 2024-10-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("state", "0023_alter_statistic_commission_profit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statistic",
            name="commission_profit",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="statistic",
            name="swap_off_ratio",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
