# Generated by Django 4.2.16 on 2024-10-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("state", "0024_alter_statistic_commission_profit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statistic",
            name="commission_off_ratio",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="statistic",
            name="swap_off_ratio",
            field=models.FloatField(default=1),
        ),
    ]
