# Generated by Django 4.2.16 on 2024-10-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0026_remove_statistic_commission_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
