# Generated by Django 5.0.6 on 2024-09-11 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('unit', models.FloatField()),
                ('min_unit', models.FloatField()),
                ('max_unit', models.FloatField()),
                ('step', models.FloatField()),
                ('min_price', models.FloatField()),
                ('buy_distance', models.FloatField()),
                ('sell_distance', models.FloatField()),
                ('commission', models.FloatField()),
                ('leverage', models.FloatField()),
                ('commission_future', models.FloatField()),
                ('commission_poursant', models.FloatField()),
                ('unit_tax', models.FloatField()),
                ('daily_swap_buy', models.FloatField()),
                ('daily_swap_sell', models.FloatField()),
                ('max_allowed_price', models.FloatField()),
                ('min_allowed_price', models.FloatField()),
                ('users', models.ManyToManyField(related_name='pairs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('ticket', models.PositiveBigIntegerField()),
                ('unit', models.FloatField()),
                ('leverage', models.FloatField()),
                ('sl', models.FloatField()),
                ('tp', models.FloatField()),
                ('state', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=8)),
                ('profit', models.FloatField()),
                ('time', models.DateTimeField()),
                ('symbol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='mt5.pairs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
