# Generated by Django 5.0.6 on 2024-09-11 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('ticket', models.PositiveBigIntegerField()),
                ('type', models.CharField(max_length=32)),
                ('dir', models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=8)),
                ('unit', models.FloatField()),
                ('leverage', models.FloatField()),
                ('sl', models.FloatField()),
                ('tp', models.FloatField()),
                ('profit', models.FloatField()),
                ('time', models.DateTimeField()),
                ('commission', models.FloatField()),
                ('symbol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='mt5.pairs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('ticket', models.PositiveBigIntegerField()),
                ('type', models.CharField(max_length=32)),
                ('unit', models.FloatField()),
                ('leverage', models.FloatField()),
                ('time', models.DateTimeField()),
                ('symbol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='mt5.pairs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.FloatField()),
                ('exit', models.FloatField()),
                ('ticket', models.PositiveBigIntegerField()),
                ('type', models.CharField(max_length=32)),
                ('unit', models.FloatField()),
                ('leverage', models.FloatField()),
                ('sl', models.FloatField()),
                ('tp', models.FloatField()),
                ('state', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=8)),
                ('profit', models.FloatField()),
                ('time', models.DateTimeField()),
                ('commission', models.FloatField()),
                ('swap', models.FloatField()),
                ('symbol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='mt5.pairs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.DeleteModel(
            name='Trades',
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['user'], name='mt5_deal_user_id_b2bc7d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='mt5_order_user_id_532bca_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user'], name='mt5_trade_user_id_a0c215_idx'),
        ),
    ]
