# Generated by Django 5.0.6 on 2024-09-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0002_deal_order_trade_delete_trades_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pairs',
            options={'verbose_name': 'Pair', 'verbose_name_plural': 'Pairs'},
        ),
        migrations.AddField(
            model_name='pairs',
            name='max_price',
            field=models.FloatField(default=2000),
            preserve_default=False,
        ),
    ]
