# Generated by Django 4.2.16 on 2024-09-13 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mt5', '0004_mt5account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mt5account',
            options={'verbose_name': 'Mt5 Account'},
        ),
        migrations.AlterField(
            model_name='trade',
            name='commission',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='sl',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='swap',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='tp',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='FutureTrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.FloatField()),
                ('type', models.CharField(max_length=32)),
                ('unit', models.FloatField()),
                ('leverage', models.FloatField()),
                ('sl', models.FloatField()),
                ('tp', models.FloatField()),
                ('symbol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='future_trades', to='mt5.pairs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
