# Generated by Django 4.2.16 on 2024-09-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0007_alter_order_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='trade_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
