# Generated by Django 4.2.16 on 2024-09-15 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0009_pairsettlement_remove_pairs_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairsettlement',
            name='pair',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='settlement_days', to='mt5.pairs'),
            preserve_default=False,
        ),
    ]
