# Generated by Django 4.2.16 on 2024-09-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0010_pairsettlement_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairsettlement',
            name='friday',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='pairsettlement',
            name='monday',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='pairsettlement',
            name='saturday',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='pairsettlement',
            name='sunday',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='pairsettlement',
            name='thursday',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='pairsettlement',
            name='tuesday',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='pairsettlement',
            name='wednesday',
            field=models.TimeField(),
        ),
    ]
