# Generated by Django 4.2.16 on 2024-09-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0012_alter_paircommission_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pairs',
            old_name='buy_distance',
            new_name='ask',
        ),
        migrations.RenameField(
            model_name='pairs',
            old_name='sell_distance',
            new_name='bid',
        ),
    ]
