# Generated by Django 4.2.16 on 2024-09-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0013_rename_buy_distance_pairs_ask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairs',
            name='high',
            field=models.FloatField(default=2050),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pairs',
            name='low',
            field=models.FloatField(default=2040),
            preserve_default=False,
        ),
    ]
