# Generated by Django 4.2.16 on 2024-09-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0014_pairs_high_pairs_low'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairs',
            name='last_update',
            field=models.TimeField(auto_now=True),
        ),
    ]
