# Generated by Django 4.2.16 on 2024-09-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0015_pairs_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairs',
            name='max_allowed_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='max_leverage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='max_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='max_unit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='min_allowed_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='min_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='min_unit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='step',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='unit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='unit_tax',
            field=models.FloatField(null=True),
        ),
    ]
