# Generated by Django 4.2.16 on 2024-09-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0017_alter_deal_profit_alter_deal_sl_alter_deal_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='sl',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='tp',
        ),
    ]
