# Generated by Django 4.2.16 on 2024-09-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0019_order_trade_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='current',
            field=models.FloatField(null=True),
        ),
    ]
