# Generated by Django 4.2.16 on 2024-09-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0021_mt5account_file_path_pairs_account_pairs_digits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairs',
            name='ask',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='bid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='digits',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='max_allowed_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='max_leverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='max_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='max_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='min_allowed_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='min_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='min_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='step',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='unit_tax',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
