# Generated by Django 4.2.16 on 2024-09-17 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mt5', '0022_alter_pairs_ask_alter_pairs_bid_alter_pairs_digits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairs',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='pairs', to=settings.AUTH_USER_MODEL, verbose_name='users (that have this symbol in their watchlist)'),
        ),
    ]
