# Generated by Django 4.2.16 on 2024-09-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0023_alter_pairs_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mt5account',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='pairs',
            name='account',
        ),
    ]
