# Generated by Django 4.2.16 on 2024-09-18 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mt5', '0024_remove_mt5account_file_path_remove_pairs_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pairs',
            old_name='max_price',
            new_name='max_balance',
        ),
        migrations.RenameField(
            model_name='pairs',
            old_name='min_price',
            new_name='min_balance',
        ),
        migrations.CreateModel(
            name='Off',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_ratio', models.FloatField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='off', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
