# Generated by Django 4.2.16 on 2024-09-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0025_rename_max_price_pairs_max_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='futuretrades',
            options={'verbose_name': 'Pending Order', 'verbose_name_plural': 'Pending Orders'},
        ),
    ]
