# Generated by Django 4.2.16 on 2024-09-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0026_alter_futuretrades_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Margin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_balance', models.FloatField(verbose_name='min balance before call margin')),
            ],
            options={
                'verbose_name': 'Margin',
            },
        ),
    ]
