# Generated by Django 4.2.16 on 2024-09-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0027_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='commission',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='swap',
            field=models.FloatField(default=0, null=True),
        ),
    ]
