# Generated by Django 4.2.16 on 2024-09-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0028_alter_trade_commission_alter_trade_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuretrades',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
