# Generated by Django 4.2.16 on 2024-09-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0029_futuretrades_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pairs',
            options={'ordering': ['name'], 'verbose_name': 'Pair', 'verbose_name_plural': 'Pairs'},
        ),
    ]
