# Generated by Django 4.2.16 on 2024-10-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0034_mt5account_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='margin',
            field=models.FloatField(default=0),
        ),
    ]
