# Generated by Django 4.2.16 on 2024-10-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0035_trade_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='margin',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='margin',
            field=models.FloatField(default=0),
        ),
    ]
