# Generated by Django 4.2.16 on 2024-10-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0036_deal_margin_order_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairswap',
            name='swap',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='step',
            field=models.FloatField(blank=True, null=True, verbose_name='Slippage'),
        ),
        migrations.AlterField(
            model_name='pairswap',
            name='swap_buy',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='pairswap',
            name='swap_buy_ratio',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='pairswap',
            name='swap_sell',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='pairswap',
            name='swap_sell_ratio',
            field=models.FloatField(default=1, null=True),
        ),
    ]
