# Generated by Django 4.2.16 on 2024-10-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0037_pairswap_swap_alter_pairs_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairs',
            name='free_margin_ratio',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
