# Generated by Django 4.2.16 on 2024-10-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0038_pairs_free_margin_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairs',
            name='commission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pairs',
            name='commission_buy_ratio',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='pairs',
            name='commission_sell_ratio',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='pairs',
            name='swap',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pairs',
            name='swap_buy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pairs',
            name='swap_buy_ratio',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='pairs',
            name='swap_sell',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pairs',
            name='swap_sell_ratio',
            field=models.FloatField(default=1),
        ),
    ]
