# Generated by Django 4.2.16 on 2024-10-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0039_pairs_commission_pairs_commission_buy_ratio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PairCommission',
        ),
    ]
