# Generated by Django 4.2.16 on 2024-10-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0040_delete_paircommission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PairSwap',
        ),
    ]
