# Generated by Django 4.2.16 on 2024-10-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0041_delete_pairswap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairs',
            name='free_margin_ratio',
        ),
        migrations.AddField(
            model_name='margin',
            name='free_margin_ratio',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
