# Generated by Django 4.2.16 on 2024-10-08 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0042_remove_pairs_free_margin_ratio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairSwap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swap', models.FloatField(default=0, null=True)),
                ('swap_buy', models.FloatField(default=1, null=True)),
                ('swap_sell', models.FloatField(default=1, null=True)),
                ('swap_buy_ratio', models.FloatField(default=1, null=True)),
                ('swap_sell_ratio', models.FloatField(default=1, null=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps', to='mt5.pairs')),
            ],
            options={
                'verbose_name': 'Swap',
                'verbose_name_plural': 'Swaps',
            },
        ),
        migrations.CreateModel(
            name='PairCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.FloatField(default=0, null=True)),
                ('commission_buy_ratio', models.FloatField(default=1, null=True)),
                ('commission_sell_ratio', models.FloatField(default=1, null=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='mt5.pairs')),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
            },
        ),
    ]
