# Generated by Django 4.2.16 on 2024-10-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0043_pairswap_paircommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairs',
            name='commission_buy',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='pairs',
            name='commission_sell',
            field=models.FloatField(default=1),
        ),
    ]
