# Generated by Django 4.2.16 on 2024-10-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mt5", "0045_remove_pairs_commission_remove_pairs_swap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pairs",
            name="commission_buy_ratio",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="pairs",
            name="commission_sell_ratio",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="pairs",
            name="swap_buy_ratio",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="pairs",
            name="swap_sell_ratio",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
