# Generated by Django 4.2.16 on 2024-10-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0050_alter_pairs_commission_buy_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairs',
            name='commission_buy_ratio',
            field=models.DecimalField(decimal_places=9, max_digits=30),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='commission_sell_ratio',
            field=models.DecimalField(decimal_places=9, max_digits=30),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='swap_buy_ratio',
            field=models.DecimalField(decimal_places=9, max_digits=30),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='swap_sell_ratio',
            field=models.DecimalField(decimal_places=9, max_digits=30),
        ),
    ]
