# Generated by Django 4.2.16 on 2024-10-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0053_alter_pairs_commission_buy_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairs',
            name='contract_size',
            field=models.FloatField(default=1),
        ),
    ]
