# Generated by Django 4.2.16 on 2024-10-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0055_alter_pairs_commission_buy_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairs',
            name='margin_varianc',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
        ),
    ]
