# Generated by Django 4.2.16 on 2024-10-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0056_pairs_margin_varianc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='margin',
            name='free_margin_ratio',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
