# Generated by Django 4.2.16 on 2024-10-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0057_alter_margin_free_margin_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairs',
            name='call_margin_ratio',
            field=models.DecimalField(decimal_places=12, default=1, max_digits=20),
        ),
    ]
