# Generated by Django 4.2.16 on 2024-10-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0058_pairs_call_margin_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='margin',
            name='callmargin_level',
            field=models.FloatField(default=50),
        ),
    ]
