# Generated by Django 4.2.16 on 2024-10-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0059_margin_callmargin_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairs',
            name='step',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
