# Generated by Django 4.2.16 on 2024-09-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_alter_message_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
