# Generated by Django 4.2.16 on 2024-09-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_alter_message_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='trade_id',
            new_name='trade',
        ),
        migrations.AlterField(
            model_name='message',
            name='code',
            field=models.CharField(choices=[('0', 'Welcome'), ('1', 'Open Trade'), ('2', 'Close Trade'), ('3', 'Modify Trade'), ('4', 'Open Order'), ('5', 'Close Order'), ('10', 'admin Message'), ('20', 'Balance increase'), ('21', 'Withdraw accept'), ('22', 'Withdraw completed'), ('99', 'Liquidate')], max_length=64, null=True),
        ),
    ]
