# Generated by Django 4.2.16 on 2024-09-20 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mt5', '0028_alter_trade_commission_alter_trade_profit_and_more'),
        ('message', '0007_message_balance_message_increased_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mt5.futuretrades'),
        ),
    ]
