# Generated by Django 4.2.16 on 2024-09-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_user_referer_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=True),
        ),
    ]
